objc_library(
    name = "sample_synth_objc",
    srcs = ["main.mm"],
    deps = ["//:midi"],
    visibility = ["//visibility:private"],
    copts = ["-std=c++20"],
)

cc_binary(
    name = "sample_synth",
    deps = [":sample_synth_objc"],
    visibility = ["//visibility:public"],
    linkopts = [
        "-framework",
        "Foundation",
        "-framework",
        "CoreFoundation",
        "-framework",
        "CoreMIDI",
        "-framework",
        "AVFAudio",
    ],
)
